name: 'Build & Publish'
on:
  push:
    branches:
      - master
      - ft/*
    tags:
      - v3*

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Windows Export
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Build Directory
        run: |
          mkdir -v -p -m777 ./samples/csharp-sample/build/windows/ 
          pwd
          ls -R -al ./samples/csharp-sample/build/
      - name: Run Export
        uses: ./
        id: export-windows
        with:
          project-path: ./samples/csharp-sample/
          export-config: Windows
          export-path:  build/windows/sample.exe
      - name: List Directory Contents
        run: |
          pwd
          ls -R -al ./samples/csharp-sample/build/
      - name: Archive Windows Export
        uses: actions/upload-artifact@v2
        with:
          name: windows-export
          path: ./samples/csharp-sample/build/windows/
  build-and-push:
    name: 'Build and Publish Docker Image'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davidwesst/godot-mono-export
          tag_with_ref: true
          push: false